PROJECT_ID = "recove-450509"
DATASET_ID = "vinted"

ITEM_ACTIVE_TABLE_ID = "item_active"
INDEX_TABLE_ID = "item_active_index"
SOLD_TABLE_ID = "sold"
PINECONE_TABLE_ID = "pinecone"

VINTED_ID_FIELD = "vinted_id"
AVAILABLE_FIELD = "is_available"

PINECONE_INDEX_NAME = "items"

BS4_PARSER = "html.parser"
REQUESTS_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
}

SOLD_CONTAINER_TYPE = "div"
SOLD_CONTAINER_ATTRS = {"data-testid": "item-status--content"}
SOLD_STATUS_CONTENT = "Vendu"

NOT_FOUND_CONTAINER_TYPE = "h1"
NOT_FOUND_CONTAINER_ATTRS = {
    "class": "web_ui__Text__text web_ui__Text__heading web_ui__Text__center"
}
NOT_FOUND_STATUS_CONTENT = "La page n'existe pas"

TOP_BRANDS = [
    "Zara",
    "Nike",
    "adidas",
    "H&M",
    "Local",
    "Shein",
    "Bershka",
    "Ralph Lauren",
    "Pull & Bear",
    "Tommy Hilfiger",
    "Lacoste",
    "Stradivarius",
    "Levi's",
    "Puma",
    "Mango",
    "Primark",
    "Kiabi",
    "Carhartt",
    "The North Face",
    "Decathlon",
    "Jordan",
    "Jack & Jones",
    "Made In Italy",
    "GUESS",
    "Celio",
    "Timberland",
    "Burberry",
    "Calvin Klein",
    "Gucci",
    "Vintage",
    "Jules",
    "Louis Vuitton",
    "Pimkie",
    "Quechua",
    "Under Armour",
    "ONLY",
    "C&A",
    "Uomo",
    "Asics",
    "sans marque",
    "Hugo Boss",
    "Salomon",
    "ASOS",
    "Dior",
    "Jennyfer",
    "Massimo Dutti",
    "Lefties",
    "New Balance",
    "Diesel",
    "Devred",
    "Vans",
    "Springfield",
    "Hollister",
    "Camaïeu",
    "Dickies",
    "Superdry",
    "Columbia",
    "Moncler",
    "Stone Island",
    "Inconnu",
    "Wed'ze",
    "Esprit",
    "Reebok",
    "Balenciaga",
    "Champion",
    "Napapijri",
    "Prada",
    "UGG",
    "FILA",
    "Promod",
    "Cache Cache",
    "Uniqlo",
    "New Era",
    "Hermès",
    "New Yorker",
    "Dr. Martens",
    "Kappa",
    "Versace",
    "Fait Main",
    "Alpinestars",
    "Vera Pelle",
    "Patagonia",
    "Desigual",
    "K-Way",
    "Dsquared2",
    "G-Star",
    "Terranova",
    "Bonobo",
    "Oakley",
    "sansnom.",
    "Gémo",
    "Kaporal",
    "Polo Ralph Lauren",
    "Boutique indépendante",
    "Vero Moda",
    "Tally Weijl",
    "Footkorner",
    "Michael Kors",
    "Disney",
    "Burton",
    "Dolce & Gabbana",
    "Levi Strauss & Co.",
    "Alcott",
    "Nike Air",
    "Ray-Ban",
    "OVS",
    "Naf Naf",
    "Converse",
    "Liu Jo",
    "Piazza Italia",
    "Pepe Jeans",
    "GANT",
    "De",
    "Barbour",
    "Valentino",
    "Gymshark",
    "Scotch & Soda",
    "The Kooples",
    "Tommy Jeans",
    "Chanel",
    "Ellesse",
    "Cartier",
    "Zara Man",
    "pas de marque",
    "Boutique Parisienne",
    "Noir",
    "Joma",
    "Emporio Armani",
    "Eastpak",
    "Morgan",
    "Etam",
    "Pandora",
    "Sandro",
    "Quiksilver",
    "moto",
    "TEX",
    "Domyos",
    "Brice",
    "Fred Perry",
    "Boss",
    "Corteiz",
    "In Extenso",
    "Parfois",
    "United Colors of Benetton",
    "CHROME",
    "New Collection",
    "Giacca",
    "Omega",
    "no brand",
    "COS",
    "s.Oliver",
    "Set",
    "Argent",
    "Abercrombie & Fitch",
    "C.P. Company",
    "Dainese",
    "Sfera",
    "Armand Thiery",
    "IKKS",
    "Arc'teryx",
    "Lana",
    "Givenchy",
    "Armani",
    "Amisu",
    "El Corte Inglés",
    "Aigle",
    "Stüssy",
    "Crivit",
    "Loro Piana",
    "Teddy Smith",
    "Umbro",
    "nessuno",
    "y2k",
    "Tom Tailor",
    "NBA",
    "Le Coq Sportif",
    "Geox",
    "Esmara",
    "Kalenji",
    "Amazon",
    "ONLY & SONS",
    "Chevignon",
    "Cortefiel",
    "Mai",
    "GAP",
    "Kipsta",
    "Zadig & Voltaire",
    "Diadora",
    "Tezenis",
    "Benetton",
    "Longchamp",
    "Woolrich",
    "Head",
    "Tiffosi",
    "Sézane",
    "Denim Co",
    "Sisley",
    "Supreme",
    "Lee",
]
