name: Item availability check with sharding

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  availability-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3, 4, 5]  
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t availability .

      - name: Run Docker Container
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
          SHARD_ID: ${{ matrix.shard }}
          TOTAL_SHARDS: 6
        run: docker run -e SECRETS_JSON -e SHARD_ID -e TOTAL_SHARDS availability